apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecr-scan-results-buildkite-plugin
  description: |
    Buildkite plugin to retrieve ECR scan results
  tags:
    - camp-sre
    - data-internal-use-only
    - users-internal
  annotations:
    github.com/project-slug: buildkite/ecr-scan-results-buildkite-plugin
    github.com/team-slug: buildkite/sre-foundations
spec:
  type: library
  owner: sre-foundations
  lifecycle: production
